s777yab/monsters-market

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/monsters_controller.rb
- app/views/monsters/index.html.erb
- Created the bases for the index page
- Created a monster named terror
- Created an html page called Index.html.erb in the folder monsters in the layout folder
- Added the each method to the page index to show the name of the monster
- Added the title, Monster Market
> crated the base for the index page

- app/controllers/monsters_controller.rb
- app/views/monsters/show.html.erb
- config/routes.rb
Created a show page for the monster that people are going to see when they click on a monster in the index page.
- create a user in your database
- create a monster with that user in your database
- load localhost:3000/monsters/:id (id stands for the ID of your existing monster)
- if loads with the correct names we are in business
> Create show page for monster

- Gemfile
- Gemfile.lock
- db/seeds.rb
- Created a seed file
- run rails db:seed and watch the magic happen
- in rails console run Monster.all then user.all and you should see the monsters and users
> Create seed file and add a faker gem

- app/controllers/monsters_controller.rb
- app/views/monsters/_form.html.erb
- app/views/monsters/new.html.erb
- config/routes.rb
Please check if there is anything I can do to improve it and let me know.
> New folder and file for a partial containing a form for the creation and editing of monsters

- app/controllers/users_controller.rb
- app/views/users/user.html.erb
- config/routes.rb
- Added route for user page
- Added view for user page
- Added method for user page
- Added basic iteration function that can list attributes of booking on the user webpage
-Added a few instances of users, monsters and bookings to DB.
Tophat 
- Can test by going on /user page
> Adding user page

- app/assets/stylesheets/components/_cards.scss
- app/views/monsters/index.html.erb
Comments
-styling the index page
> Creating index page for monsters

- app/controllers/bookings_controller.rb
- app/controllers/monsters_controller.rb
- app/views/monsters/show.html.erb
- config/routes.rb
- Booking from was added by me to the show page of a monster
- Check the monster show page fill out the form with starting date submit
- Check on the user page if the booking has been added
> Create a form for booking

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/layouts/application.html.erb
- app/views/monsters/show.html.erb
- config/routes.rb
- fixed bugs in booking form wasn't raising an error upon wrong input
- In the show page create a booking
> Fix bugs on booking form

- db/seeds.rb
- hard coded users, monsters and bookings using faker and open-uri
- manually input addresses and images
Have a look friends!
> coded seed files

- app/controllers/monsters_controller.rb
- app/views/monsters/edit.html.erb
Description
-Added method for edit and update in MonstersController
Tophat🎩
-Links on dashboard work for editing monsters
> Added new/update function

- app/controllers/reviews_controller.rb
- app/views/monsters/show.html.erb
- Small bug was in simple forms
## Tophat 🎩 
- Just load the show page
> Fix bug in simple form

- .gitignore
- app/controllers/application_controller.rb
Added  authenticating user before_action which takes user to login page if they are not logged in.
> added logged-in authentication

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/monsters/index.html.erb
> New create index page for monsters

- config/environments/production.rb
- Added cloudinary to heroku config
- Once we merge go to https://monsters-market-d329a9844821.herokuapp.com/monsters/1
> Add cloudinary to heroku config

- app/assets/stylesheets/components/_booking_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_show_monster_card.scss
- app/views/monsters/show.html.erb
- Added some styling to the show page
- Just load up the show page and try the forms
> Create front end for show

- app/assets/stylesheets/components/_show_monster_card.scss
- app/views/monsters/show.html.erb
- Added a display div for the reviews
- Try to make a review
- Check the display under the review form
> Create a div for the reveiws to be displayed

- app/assets/stylesheets/components/_cards.scss
- app/views/users/user.html.erb
Description
- Added cards for "my booking"
-  Image has not implemented cloudinary yet
> Bookings cards

- app/views/users/user.html.erb
Description
- Booking card shows correct image now
> cloudinary implemented in booking cards

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
Just removed email from nav-bar and added the logout button which is a drop-down from the user icon.
> edited navbar

- app/views/layouts/application.html.erb
> added margins on application.html.erb

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/monsters/index.html.erb
-finished the card with picture
-need to center the button 
-add a footer ?
> create front-end for index page

- app/assets/stylesheets/components/_index.scss
Description
- Removed button stylesheet from index.scss imports to resolve conflict
> removed import button stylesheet from index.scss

- app/assets/stylesheets/components/_cards.scss
- app/views/users/user.html.erb
Description
- Adding basic monster card to user page
> made basic monster cards for user page

- app/views/monsters/index.html.erb
- app/views/users/user.html.erb
Added delete link to monster card on user page
> added back delete monster link to monster card on user page

- app/models/monster.rb
- Create validations for presence of attributes for monster
- Add a validation for photo
> Validations for Monster

- app/assets/stylesheets/components/_show_monster_card.scss
- app/views/monsters/show.html.erb
- Implemented some of the feedback we have gotten during the demo
1. address
2. Reviews form is too wide reviews could be displayed side by side with form
3. Humanise CTAs
- Go to the show page of any monster
- Images cannot change size
> change the front end for show page

- app/assets/stylesheets/components/_popup_monster.scss
- app/javascript/controllers/map_controller.js
- app/views/monsters/_popup_monster.html.erb
- Added the images to popups
- Added a button to the popups
- Click on any popup on the index page map
> Add image popup and some style

- app/models/user.rb
- db/migrate/20231123110337_add_first_name_to_user.rb
- db/migrate/20231123110411_add_last_name_to_users.rb
- db/migrate/20231123110440_add_username_to_users.rb
- db/schema.rb
- db/seeds.rb
- Added a coliumn for first name
- Added a coliumn for last name
- Added a coliumn for username
- Added a basic validation for User model
- Run rails db:migrate
- Run rails db:seed
> add first name last name user name to user

- app/assets/stylesheets/components/_cards.scss
- app/controllers/monsters_controller.rb
- app/views/monsters/index.html.erb
- db/seeds.rb
- Updated the seed file
- Changed the monsters controller to display only the same monsters from the map
- Updated the title of index page
- Turned the cards into links
- Rails db:migrate (optional but recommended)
- Rails db:seed
- Load the index page
> display same monsters on index as on map

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/monsters_controller.rb
- app/models/monster.rb
- app/views/monsters/index.html.erb
Description
- Added a search bar with basic styling to index page above cards
- Can search by monster attributes or by user email
> added search bar above monster cards which can search by monster or user

- app/controllers/monsters_controller.rb
- db/seeds.rb
- Updated the seed file
- Fixed a bug in the index page where booked monsters were popping up
- Load the index page with users tony and alan (You shouldn't see "Booked monster!" on index but in bookings of alan)
> Fix a bug in gecoding for booked monsters

- app/controllers/monsters_controller.rb
- Fixed a bug in index page
- Now the search works and the map as well
- Load the index page a search for monster name, species and user email
> Fix bug on index in search

- app/controllers/monsters_controller.rb
- Fixed bug in show page
- Load the show page of any monster
> Fix bug on show page

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/views/users/user.html.erb
##comment
-fixed size of the pics on my booking
-changed style of my bookings and my monsters
> Fixing pics pn dashboard page

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_search_bar.scss
- app/controllers/monsters_controller.rb
- app/views/monsters/index.html.erb
- db/seeds.rb
- Put the search bar to the top
- Created the grid for the monsters
- Put the map to the right
- Try to search for some pokemon or a user on the index page
> front edn layout of index page

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- just changed some css in the navbar and landing page
- not final but has some improvements
- has a navbar, banner, description and footer.
> Continue landing page

- app/assets/stylesheets/components/_show_monster_card.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/users/user.html.erb
-changed style of the buttons
-changed the order to see my monsters and my bookings
-created a page called _dashboards.scss
> finished style of dashboard

- app/views/monsters/index.html.erb
- In the search bar the link stays on index page
- Try and search for something
> Fix links in the whole app

- app/assets/stylesheets/components/_cards.scss
- app/views/monsters/show.html.erb
Description
- Added styling to reviews
- Now shows username and avatar and changed star icon
> Styled the reviews to have username and avatar

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_show_monster_card.scss
- app/views/shared/_navbar.html.erb
- Gave some styling to the index cards
- Some margin on the nvabar
- Just load the show and index page
> Style navbar along with cards

- app/models/monster.rb
Description
- Added monster address attribute to search function in Monster model
> added address attribute to search function in Monster model

- app/views/users/user.html.erb
> fix a bug with the pics in my monsters

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
-A lot of display flex and adding divs
-Also a lot of css
> added css/display-flex

- app/assets/stylesheets/components/_show_monster_card.scss
- app/views/monsters/show.html.erb
- Added a scrollable reviews display
- Pushed the rating to the right
- Create a couple of reveiws and scroll away!!
> Create a scrollable reviews and some minor changes to review layout

- app/models/booking.rb
- app/models/monster.rb
- db/seeds.rb
- Added a validation that a user cannot book their monster
- Populated the seed file with gecodable data and added abundace of data
- Fixed bug in seed file
- Try to book a monster that you own (it doesn't show red but it won't let you go further)
- You can load the index page and it will nicely show a you a populated map
> validations booking and reveiw model

- app/controllers/bookings_controller.rb
- app/models/monster.rb
- app/views/monsters/show.html.erb
Description
- Book monster button doesn't work if you own monster
- Displays error flash message
> Disable book button on show if own monster

- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- app/views/monsters/index.html.erb
- app/views/shared/_navbar.html.erb
- The navbar is sticky
- Navbar has a title
- Container has a margin for the whole page
- Just go to landing page and scroll
> Stick navbar to the top add title to navbar and add margin

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- added icons
- changed background color
- moved around links
- fixed spelling errors
> added icons

- app/controllers/monsters_controller.rb
## Search works for all monsters
- User can search for all and it will show tham all monsters in the world
- Refactored the code a little
- Type "all" in search
> Add search for all monsters and refactor monsters controller

- app/controllers/monsters_controller.rb
- Fixed loading of the index page it loads even without query
- Load the index page and search for nothing
> Fix bug in search

- app/assets/stylesheets/components/_cards.scss
- app/views/users/user.html.erb
- made the my booking and my monsters scrollable
- changed the name of the edit button to just edit
- changed the name of the add list to add monsters
> made the booking and monsters scrollable on the show page

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
##Description
- Fixed start button hover
- buttons in description below are sized appropriately in their respective divs
> more css, fixed buttons, a lot of flexbox

- app/assets/stylesheets/components/_cards.scss
- app/views/monsters/show.html.erb
Description
-Added a no review message to reviews box on show page
-Disappears when reviews added
> No reviews message shows when no reviews for monster

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- Find out more button works and scrolls you down
- Monster images added on Landing page
> Images on landing

- app/assets/stylesheets/config/_fonts.scss
- Added new fonts to the app
- Just load up the page
> Add Raleway and Quattrocento Sans fonts to the app

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/users/user.html.erb
##
-modified buttons with icons 
-modified positions of the buttons
> Buttons on dashboard

- app/assets/stylesheets/components/_search_bar.scss
- app/views/monsters/index.html.erb
Description
-Added a no searches found message with picture
> no search found message added with picture

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_tracking.scss
- app/controllers/users_controller.rb
- app/javascript/controllers/tracking_controller.js
- app/views/users/_tracking_popup.html.erb
- app/views/users/user.html.erb
- Added a map to the dashboard that tracks your monsters
- Load up the dashboard
- Make a monster and check the map
> add tracking to user

- app/assets/stylesheets/config/_fonts.scss
Description
- Changed heading font in the config stylesheet
> changed heading font

- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_tracking.scss
- app/views/users/user.html.erb
- Added border radius to the maps
- Just go to dashboard
- Go to index
> Add border radius to maps

- app/controllers/monsters_controller.rb
Just removed one line to make landing page work
> removed auth

- app/views/shared/_navbar.html.erb
> Navbar now displays username rather than email

- app/assets/stylesheets/components/_navbar.scss
- app/views/monsters/show.html.erb
Description
- Comment box in review form is now inline
> fixed review comment box alignment

- app/assets/stylesheets/components/_cards.scss
> added margin to all card-trip

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/users/user.html.erb
-modified the add monster button
> Moving add monster button

- app/assets/stylesheets/components/_cards.scss
Description
-Changed be first to review to a lighter colour so its stands out less
> made be first to review a lighter colour

- app/views/monsters/show.html.erb
Description
- Made booking button bigger, green and added a small shadow
> made button bigger, added small shadow and made green

- app/assets/stylesheets/components/_cards.scss
- app/views/monsters/show.html.erb
- app/views/users/user.html.erb
> changed color buttons

- app/assets/stylesheets/components/_search_bar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/monsters/index.html.erb
- app/views/pages/home.html.erb
Description
- fixed positioning of start button on landing page and changed text
- Added header describing search results
> UI fixes before demo

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_search_bar.scss
- app/views/monsters/index.html.erb
- app/views/monsters/show.html.erb
- app/views/users/user.html.erb
-changed color to all the buttons
> Changing icons colors and button

- app/views/monsters/_popup_monster.html.erb
- app/views/users/_tracking_popup.html.erb
#comment 
-changed the last buttons color
> changed the last buttons color
